name: DLP-Panorama-Install

# label used for menu selection
label: |
  Configure Panorama for Enterprise DLP Service Trial

description: |
  This skillet will check that Panorama has the latest content, cloud services plugin 1.6.0, and DLP service is connected.
  If any of these are missing, the skillet will perform the steps to get Panorama concencted to the DLP service.
type: workflow

# Labels allow grouping and type specific options and are generally only used in advanced cases
labels:
  order: 1
  collection: DLP

# variables define the things an operator may customize in this skillet. Things like DNS servers, NTP addresses, etc
# may be customized for each deployment. Each variable will be rendered as a form field in the panhandler application
variables:
  - name: TARGET_IP
    description: Host
    default: 127.0.0.1
    type_hint: fqdn_or_ip
  - name: TARGET_USERNAME
    description: Username
    default: admin
    type_hint: text
  - name: TARGET_PASSWORD
    description: Password
    default: admin
    type_hint: password
  - name: cloud_service_plugin
    description: cloud services plugin version
    default:
    type_hint: hidden

# Snippets is an ordered list of configuration xml fragments that will be pushed to the PAN-OS NGFW. The xpath
# determines where in the configuration hierarchy the xml fragment will be set. 'file' indicates the name of the file
# to load and parse. Jinja2 style variables will be variable interpolated using the values of the 'variables' defined
# in the 'variables' section.
snippets:
  - name: get_cloud_services_plugin_version
  - name: DLP-Verify-Panorama
  - name: DLP-Panorama-Install
    when: cloud_service_plugin < '1.6.0'
  - name: DLP-Verify-Panorama
    when: cloud_service_plugin < '1.6.0'