name: get_cloud_services_plugin_version

label: Checks the Cloud Services Plugin version on Panorama

description: |
  Get Cloud Services Plugin from Panorama
type: rest

labels:
  collection:
    - DLP

variables:
  - name: TARGET_IP
    description: Host
    default: 10.70.221.159
    type_hint: hidden
  - name: TARGET_USERNAME
    description: Username
    default: admin
    type_hint: hidden
  - name: TARGET_PASSWORD
    description: Password
    default: Paloalto1
    type_hint: hidden
snippets:
  - name: key_gen
    path: https://{{ TARGET_IP }}/api/?type=keygen&user={{ TARGET_USERNAME }}&password={{ TARGET_PASSWORD }}
    output_type: xml
    outputs:
      - name: api_key
        capture_pattern: result/key
  - name: plugin_version
    path: |
      https://{{ TARGET_IP }}/api/?type=op&cmd=<show><system><info></info></system></show>&key={{ api_key }}
    output_type: xml
    outputs:
      - name: cloudservice_plugin_version
        capture_value: result/system/plugin_versions/entry[@name='cloud_services']/@version

