# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: DLP-Verify-Panorama
# label used for menu selection
label: Verify Panorama is ready for Enterprise DLP
description: |
  Skillet to test whether Panorama is connected to Enterprise DLP and ready
  to build policies leveraging advanced DLP Data Patterns and Data Profiles


type: pan_validation

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - DLP
    - Validation

# ---------------------------------------------------------------------
# end of preamble section

# snippets section
# ---------------------------------------------------------------------
snippets:
# test for Cloud Services Plugin 1.5.0 or greater
  - name: cloud_services
    cmd: parse
    variable: config
    outputs:
      - name: cloud_service_plugin
        capture_value: /config/devices/entry[@name='localhost.localdomain']/plugins/cloud_services/@version

  - name: check_version
    label: Check plugin version
    test: cloud_service_plugin >= '1.5.0'
    documentation_link: https://docs.paloaltonetworks.com/prisma/prisma-access/prisma-access-panorama-release-notes/prisma-access-about/upgrade-cloud-services-plugin
    fail_message: |
      Cloud Services Plugin version {{ cloud_service_plugin }} fails requirement (1.5.0 or greater)
    pass_message: |
      Cloud Services Plugin version {{ cloud_service_plugin }} meets requirement (1.5.0 or greater)

# Check for Enterprise DLP specific data pattern and data filtering profile objects
  - name: device_config_file
    cmd: parse
    variable: config
    outputs:
      - name: GDPR_profile
        capture_object: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='Remote_Network_Device_Group']/profiles/dlp-data-profiles/entry[@name='GDPR']
      - name: BulkCCN_profile
        capture_object: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='Remote_Network_Device_Group']/profiles/dlp-data-profiles/entry[@name='Bulk CCN']

      - name: Garbage_profile
        capture_object: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='Remote_Network_Device_Group']/profiles/dlp-data-profiles/entry[@name='Garbage']

  - name: GDPR_profile_test
    label: Check for presence of pre-defined data pattern and
            data profile from Enterprise DLP Service
    when: cloud_service_plugin >= '1.5.0'
    test: |
     (
      GDPR_profile | attribute_present('entry', 'name', 'GDPR')
      and GDPR_profile | element_value('id') == '11995013'
      and GDPR_profile | attribute_present('rule1.patterns.entry', 'name', 'Driver License - Bulgaria')
      and GDPR_profile | attribute_present('rule1.patterns.entry', 'name', 'Driver License - Austria')
      and GDPR_profile | attribute_present('rule1.patterns.entry', 'name', 'Driver License - Belgium')
      and GDPR_profile | attribute_present('rule1.patterns.entry', 'name', 'Driver License - Germany')
      and GDPR_profile | attribute_present('rule1.patterns.entry', 'name', 'Driver License - Czech Republic')
      and GDPR_profile | attribute_present('rule1.patterns.entry', 'name', 'Driver License - Denmark')
      and GDPR_profile | attribute_present('rule1.patterns.entry', 'name', 'Driver License - Spain')
      and GDPR_profile | attribute_present('rule1.patterns.entry', 'name', 'Passport - Bulgaria')
      and GDPR_profile | attribute_present('rule1.patterns.entry', 'name', 'Passport - Austria')
      and GDPR_profile | attribute_present('rule1.patterns.entry', 'name', 'Passport - Belgium')
      and GDPR_profile | attribute_present('rule1.patterns.entry', 'name', 'Passport - Germany')
      and GDPR_profile | attribute_present('rule1.patterns.entry', 'name', 'Passport - Czech Republic')
      and GDPR_profile | attribute_present('rule1.patterns.entry', 'name', 'Passport - Denmark')
      and GDPR_profile | attribute_present('rule1.patterns.entry', 'name', 'Passport - Spain')
     )
    fail_message: |
      Enterprise DLP has not been enabled, please request trial from Panorama > Cloud Services Configuration (Setup Tab)
      or contact your Palo Alto Networks Systems Engineer for assistance
      {{ GDPR_profile }}
#    pass_message: Enterprise DLP Data Pattenrs and Data Profles are ready for use in Policy
    severity: High
    documentation_link: https://www.paloaltonetworks.com/resources/datasheets/enterprise-data-loss-prevention

  - name: BulkCCN_profile_test
    label: Check for presence of pre-defined data pattern and
            data profile from Enterprise DLP Service
    when: ((GDPR_profile_test.results != true ) and ( BulkCCN_profile is none or BulkCCN_profile | element_value('entry.id') != '11995001' ))
    test: false
    fail_message: |
      Enterprise DLP Bulk CCN Profile missing, please request trial from Panorama > Cloud Services Configuration (Setup Tab)
      or contact your Palo Alto Networks Systems Engineer for assistance

    pass_message:
    severity: High
    documentation_link: https://www.paloaltonetworks.com/resources/datasheets/enterprise-data-loss-prevention

  - name: Garbage_profile_test
    label: Check for presence of pre-defined data pattern and
            data profile from Enterprise DLP Service
    when: ( Garbage_profile is none or Garbage_profile | element_value('id') != '11995010' )
    test: false
    fail_message: |
      Enterprise DLP Garbage Profile mising, please request trial from Panorama > Cloud Services Configuration (Setup Tab)
      or contact your Palo Alto Networks Systems Engineer for assistance

    pass_message:
    severity: High
    documentation_link: https://www.paloaltonetworks.com/resources/datasheets/enterprise-data-loss-prevention
# ---------------------------------------------------------------------
# end of snippets section