# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: DLP-Verify-Panorama
# label used for menu selection
label: DLP-Verification-Panorama
description: Skillet to test whether Panorama is connected to Enterprise DLP and ready to build policies leveraging advanced DLP Data Patterns and Data Profiles

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: pan_validation
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - DLP

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints examples include text, ip_address, or dropdown

variables:
  - name: hostname
    description: Panorama hostname or IP address
    default: Panorama
    type_hint: text
#  - name: choices
#    description: sample dropdown list
#    default: choices
#    type_hint: dropdown
#    dd_list:
#      - key: option1
#        value: option1
#      - key: option2
#        value: option2
  - name: snippets
    type_hint: hidden
    default: ''
# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
snippets:
# test for Cloud Services Plugin 1.5.0 or greater
  - name: cloud_services
    cmd: parse
    variable: config
    outputs:
      - name: cloud_services_plugin
        capture_object: /config/devices/entry[@name='localhost.localdomain']/plugins/cloud_services

  - name: cloud_services_version
    label: Cloud Services Version
    test: |
      (
      cloud_services_plugin | attribute_present('cloud_services', 'version', '1.5.0')
      )
    fail_message: |
      Cloud Services Plugin not installed or does not support Enterprise DLP.
      Please update to Cloud Services Plugin version 1.5.0 or greater.
    pass_message: Cloud Services Plugin 1.5.0 or greater found
    severity: High
    documentation_link: https://docs.paloaltonetworks.com/prisma/prisma-access/prisma-access-panorama-release-notes/prisma-access-about/upgrade-cloud-services-plugin

# Check for Enterprise DLP specific data pattern and data filtering profile objects
  - name: device_config_file
    cmd: parse
    variable: config
    outputs:
      - name: dlp_profile
        capture_object: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='Remote_Network_Device_Group']/profiles/dlp-data-profiles/entry[@name='GDPR']

  - name: GDPR_profile_test
    label: Check for presence of pre-defined data pattern and
            data profile from Enterprise DLP Service
    when: cloud_services_plugin | attribute_present('cloud_services', 'version', '1.5.0')
    test: |
     (
      dlp_profile | attribute_present('entry', 'name', 'GDPR')
      and dlp_profile | element_value('id') == '11995013'
      and dlp_profile | attribute_present('rule1.patterns.entry', 'name', 'Driver License - Bulgaria')
      and dlp_profile | attribute_present('rule1.patterns.entry', 'name', 'Driver License - Austria')
      and dlp_profile | attribute_present('rule1.patterns.entry', 'name', 'Driver License - Belgium')
      and dlp_profile | attribute_present('rule1.patterns.entry', 'name', 'Driver License - Germany')
      and dlp_profile | attribute_present('rule1.patterns.entry', 'name', 'Driver License - Czech Republic')
      and dlp_profile | attribute_present('rule1.patterns.entry', 'name', 'Driver License - Denmark')
      and dlp_profile | attribute_present('rule1.patterns.entry', 'name', 'Driver License - Spain')
      and dlp_profile | attribute_present('rule1.patterns.entry', 'name', 'Passport - Bulgaria')
      and dlp_profile | attribute_present('rule1.patterns.entry', 'name', 'Passport - Austria')
      and dlp_profile | attribute_present('rule1.patterns.entry', 'name', 'Passport - Belgium')
      and dlp_profile | attribute_present('rule1.patterns.entry', 'name', 'Passport - Germany')
      and dlp_profile | attribute_present('rule1.patterns.entry', 'name', 'Passport - Czech Republic')
      and dlp_profile | attribute_present('rule1.patterns.entry', 'name', 'Passport - Denmark')
      and dlp_profile | attribute_present('rule1.patterns.entry', 'name', 'Passport - Spain')
     )
    fail_message: |
      Enterprise DLP has not been enabled, please request trial from Panorama > Cloud Services Configuration (Setup Tab)
      or contact your Palo Alto Networks Systems Engineer for assistance
      {{ dlp_profile }}
    pass_message: Enterprise DLP Data Pattenrs and Data Profles are ready for use in Policy
    severity: High
    documentation_link: https://www.paloaltonetworks.com/resources/datasheets/enterprise-data-loss-prevention

# ---------------------------------------------------------------------
# end of snippets section